apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-techdocs-sample
  annotations:
    github.com/project-slug: sugonoda/backstage-techdocs-sample
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: guests
